services:
  db:
    image: postgres:16
    container_name: homelab-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-homelab}
      POSTGRES_USER: ${POSTGRES_USER:-homelab}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-homelab}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d

  api:
    build:
      context: ./backend
    container_name: homelab-api
    restart: unless-stopped
    depends_on:
      - db
    environment:
      # NOTE: host is "db" because compose service name
      DATABASE_URL: postgresql+psycopg2://${POSTGRES_USER:-homelab}:${POSTGRES_PASSWORD:-homelab}@db:5432/${POSTGRES_DB:-homelab}
      CORS_ALLOWED_ORIGINS: http://localhost:3000,http://localhost:5173
      OLLAMA_URL: ${OLLAMA_URL}
      OLLAMA_MODEL: ${OLLAMA_MODEL}
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY}
      ANTHROPIC_MODEL: claude-haiku-4-5
    ports:
      - "8000:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  web:
    build:
      context: ./frontend/web
    container_name: homelab-web
    restart: unless-stopped
    ports:
      - "5173:5173"
    depends_on:
      - api

volumes:
  pgdata:
