-- Drop and recreate table
DROP TABLE IF EXISTS tarot_cards;

CREATE TABLE tarot_cards (
    id SERIAL PRIMARY KEY,
    name TEXT NOT NULL,
    arcana TEXT NOT NULL,
    short_meaning TEXT NOT NULL,
    full_summary TEXT NOT NULL
);

-- Insert all 78 tarot cards
INSERT INTO tarot_cards (name, arcana, short_meaning, full_summary) VALUES
-- Major Arcana
('The Fool', 'Major',
 'Beginnings, spontaneity, optimism, taking a leap of faith',
 'The Fool stands at the threshold of everything. This carefree character faces the unknown unmolded by the lessons of life experience. Anything can happen, and you have much to learn. Listen to your instincts and let the teachers around you guide your journey forth.'),
('The Magician', 'Major',
 'Manifestation, skill, resourcefulness, focused action',
 'The Magician channels willpower into form. This card invites you to recognize the tools, skills, and resources already at your disposal. When you align intention with action, you can turn ideas into reality and shape your circumstances with conscious choice.'),
('The High Priestess', 'Major',
 'Intuition, hidden knowledge, mystery, inner wisdom',
 'The High Priestess stands at the veil between seen and unseen. She calls you inward to trust your intuition and the quiet voice of inner truth. Not everything is ready to be revealed, so be patient and allow mysteries to unfold in their own time.'),
('The Empress', 'Major',
 'Abundance, fertility, creativity, nurturing energy',
 'The Empress embodies warmth, comfort, and natural abundance. She encourages you to nourish yourself and others, and to honor your creative cycles. Growth is possible when you create a supportive environment and treat your body, relationships, and projects with care.'),
('The Emperor', 'Major',
 'Authority, structure, leadership, stability',
 'The Emperor represents order, stability, and grounded leadership. This card invites you to set clear boundaries, make firm decisions, and take responsibility for your domain. When you combine discipline with integrity, you create a foundation that others can rely on.'),
('The Hierophant', 'Major',
 'Tradition, spiritual guidance, conformity, established beliefs',
 'The Hierophant speaks of tradition, systems, and shared beliefs. You may be seeking guidance from a mentor, teacher, or institution. This card suggests learning from established wisdom while also questioning which rules still serve your growth and which you may release.'),
('The Lovers', 'Major',
 'Choices, relationships, alignment, harmony',
 'The Lovers highlights connection, values, and important choices. It may point to a meaningful relationship or to a decision that must align with your deepest truth. When your actions match your heart and values, you create harmony within yourself and with others.'),
('The Chariot', 'Major',
 'Willpower, determination, victory, control',
 'The Chariot is a symbol of motion, resolve, and focused direction. This card urges you to harness opposing forces and move forward with discipline. Success is possible when you stay centered, steer your energy with intention, and refuse to be pulled off course.'),
('Strength', 'Major',
 'Courage, patience, compassion, inner strength',
 'Strength reflects calm courage and gentle power. Instead of brute force, it asks for compassion, patience, and steady presence. By befriending your fears and instincts rather than fighting them, you discover a deeper and more enduring form of inner strength.'),
('The Hermit', 'Major',
 'Introspection, solitude, searching for truth',
 'The Hermit steps away from noise to seek clarity in solitude. This card invites you to turn inward, reflect, and listen for your own wisdom. Through quiet observation and patience, you can discover answers that no external source can fully provide.'),
('Wheel of Fortune', 'Major',
 'Change, cycles, fate, luck turning',
 'The Wheel of Fortune reminds you that life moves in cycles. Fortunes rise and fall, and circumstances shift in unexpected ways. This card encourages you to stay flexible, recognize patterns, and participate wisely in the changes that are now unfolding.'),
('Justice', 'Major',
 'Fairness, truth, cause and effect, balance',
 'Justice brings attention to fairness, accountability, and truth. Your choices carry consequences, and this card asks you to act with integrity. Weigh the facts carefully, listen for clarity, and be willing to take responsibility for both past actions and current decisions.'),
('The Hanged Man', 'Major',
 'Letting go, new perspective, surrender',
 'The Hanged Man pauses and hangs in suspension to see the world differently. You are invited to release control, accept delay, or sacrifice an old viewpoint. By surrendering to a new perspective, you may discover insights that were previously out of reach.'),
('Death', 'Major',
 'Transformation, endings, rebirth, transition',
 'Death marks a powerful transition and the end of a chapter. While endings can feel difficult, they clear space for new growth and possibilities. This card asks you to accept what is complete, honor your grief, and step toward transformation without clinging to what has passed.'),
('Temperance', 'Major',
 'Balance, moderation, healing, blending energies',
 'Temperance symbolizes harmony and the art of mixing opposites. It calls you to moderation, patience, and the careful blending of different aspects of your life. Through balance and steady adjustment, you can find a peaceful middle path and long term healing.'),
('The Devil', 'Major',
 'Temptation, materialism, bondage, unhealthy attachments',
 'The Devil points to patterns of bondage, temptation, or self limitation. You may feel trapped by habits, relationships, or beliefs that drain your power. This card urges you to face these attachments honestly and remember that you hold the key to your own chains.'),
('The Tower', 'Major',
 'Sudden change, upheaval, revelation, breakdown for renewal',
 'The Tower signals sudden disruption, shock, or a crumbling of false structures. Though unsettling, it clears away what cannot stand, revealing hidden truths. This card invites you to release rigid expectations and rebuild on a more authentic and solid foundation.'),
('The Star', 'Major',
 'Hope, inspiration, clarity, renewal',
 'The Star shines after turmoil, offering peace, hope, and gentle guidance. It reminds you that healing is possible and that your inner light still burns. Trust in your future, nourish your spirit, and move forward with calm faith in the path that unfolds.'),
('The Moon', 'Major',
 'Illusion, fear, subconscious, uncertainty',
 'The Moon illuminates dreams, fears, and shifting impressions. You may be walking through uncertainty or misunderstanding. This card encourages you to question appearances, honor your intuitive feelings, and move slowly while you navigate the shadows of the unknown.'),
('The Sun', 'Major',
 'Joy, success, vitality, positivity',
 'The Sun radiates warmth, clarity, and success. It suggests a time of confidence, ease, and honest self expression. This card encourages you to step into visibility, celebrate your achievements, and trust that life can be bright, open, and supportive.'),
('Judgement', 'Major',
 'Awakening, evaluation, reckoning, inner calling',
 'Judgement announces a call to awaken, review, and renew. You are invited to look honestly at your past, forgive what you can, and release what no longer serves. By answering your deeper calling, you move into a new phase with greater clarity and self acceptance.'),
('The World', 'Major',
 'Completion, accomplishment, fulfillment, wholeness',
 'The World represents completion, integration, and a sense of arriving. A cycle has come full circle, and you can recognize how far you have grown. This card invites you to celebrate your progress and prepare for a new journey that begins from a place of wholeness.');

-- Wands
INSERT INTO tarot_cards (name, arcana, short_meaning, full_summary) VALUES
('Ace of Wands', 'Minor - Wands',
 'New inspiration, creative spark, potential',
 'The Ace of Wands ignites a spark of creativity, desire, or passion. It marks the start of an inspiring project, urge, or direction. This card encourages you to act on your excitement, explore new territory, and trust the energy that is trying to move through you.'),
('Two of Wands', 'Minor - Wands',
 'Planning, decisions, forward vision',
 'The Two of Wands stands at the doorway between where you are and where you could go next. You may be planning, weighing options, or envisioning a larger life. This card suggests expanding your horizons and choosing the path that aligns with your long term vision.'),
('Three of Wands', 'Minor - Wands',
 'Expansion, progress, opportunities unfolding',
 'The Three of Wands looks out over distant shores with anticipation. Your efforts are beginning to take form, and future opportunities are approaching. This card encourages patience, confidence, and readiness to receive what your earlier choices set in motion.'),
('Four of Wands', 'Minor - Wands',
 'Celebration, harmony, foundations, community',
 'The Four of Wands marks a moment of stability and joyful recognition. It often points to celebration, milestones, or supportive community. This card invites you to pause, appreciate your foundation, and share your happiness with others around you.'),
('Five of Wands', 'Minor - Wands',
 'Conflict, competition, challenges',
 'The Five of Wands shows clashing wills, competition, or scattered energy. You may be wrestling with disagreements, internal tension, or rivalry. This card suggests focusing on fair play, clear communication, and constructive ways to channel your drive.'),
('Six of Wands', 'Minor - Wands',
 'Victory, success, recognition',
 'The Six of Wands rides forward in triumph. It signals recognition for your work, a win after effort, or renewed confidence. This card encourages you to own your achievements with humility and to keep moving in alignment with your strengths and values.'),
('Seven of Wands', 'Minor - Wands',
 'Defensiveness, standing your ground, perseverance',
 'The Seven of Wands stands on higher ground, defending hard won progress. You may feel challenged or pressured to justify your position. This card urges you to hold firm where it matters, believe in your choices, and persist through temporary resistance.'),
('Eight of Wands', 'Minor - Wands',
 'Swift movement, progress, communication',
 'The Eight of Wands flies fast through the air, symbolizing acceleration and flow. Events may be moving quickly, and messages or opportunities can arrive at once. This card encourages direct communication and decisive action while momentum is on your side.'),
('Nine of Wands', 'Minor - Wands',
 'Resilience, boundaries, persistence',
 'The Nine of Wands stands guarded yet unbroken after many trials. You may feel tired but close to completion. This card calls for resilience, wise boundaries, and cautious optimism as you navigate the final stretch of a demanding situation.'),
('Ten of Wands', 'Minor - Wands',
 'Burdens, hard work, responsibility overload',
 'The Ten of Wands carries a heavy load toward the finish line. Responsibility, obligation, or overcommitment may weigh you down. This card suggests delegating, prioritizing, and letting go of what is not truly yours so you can move forward more freely.'),
('Page of Wands', 'Minor - Wands',
 'Exploration, enthusiasm, new ideas',
 'The Page of Wands is an eager messenger of inspiration. Curiosity, adventure, and playful experimentation call to you now. This card invites you to explore new interests, take small bold steps, and treat your creative impulses as a journey of discovery.'),
('Knight of Wands', 'Minor - Wands',
 'Action, adventure, impulsiveness',
 'The Knight of Wands charges ahead with fiery passion and bold intent. You may feel restless, adventurous, or hungry for change. This card encourages courageous action, while also reminding you to stay mindful of impulsive choices and unfinished projects.'),
('Queen of Wands', 'Minor - Wands',
 'Confidence, independence, charisma, determination',
 'The Queen of Wands radiates warmth, magnetism, and self assurance. She moves through life with creative fire and a generous spirit. This card invites you to claim your space, trust your talents, and lead by being fully and authentically yourself.'),
('King of Wands', 'Minor - Wands',
 'Leadership, vision, entrepreneurship, bold action',
 'The King of Wands embodies visionary leadership and decisive energy. He sees the bigger picture and is willing to take calculated risks. This card calls you to step into a guiding role, stay loyal to your purpose, and inspire others through action.');

-- Cups
INSERT INTO tarot_cards (name, arcana, short_meaning, full_summary) VALUES
('Ace of Cups', 'Minor - Cups',
 'Emotional beginnings, love, intuition, creativity',
 'The Ace of Cups overflows with feeling, connection, and spiritual refreshment. It heralds new emotional openings, such as love, compassion, or creative flow. This card invites you to receive and share heartfelt energy with openness and trust.'),
('Two of Cups', 'Minor - Cups',
 'Partnership, mutual attraction, unity',
 'The Two of Cups shows two people meeting heart to heart. It highlights mutual respect, affection, or balanced partnership. This card suggests building relationships based on honesty, emotional presence, and shared understanding.'),
('Three of Cups', 'Minor - Cups',
 'Friendship, celebration, community, joy',
 'The Three of Cups dances in a circle of friendship and support. It points to gatherings, shared joy, and emotional uplift from community. This card encourages you to celebrate your connections and let others share in your happiness and healing.'),
('Four of Cups', 'Minor - Cups',
 'Apathy, contemplation, reevaluation',
 'The Four of Cups sits in quiet discontent, focused on what feels stale. You may feel bored, withdrawn, or disconnected from what is offered. This card invites you to look inward, reassess your emotional needs, and notice new possibilities that may be easy to overlook.'),
('Five of Cups', 'Minor - Cups',
 'Loss, regret, grief, focusing on what is left',
 'The Five of Cups grieves over spilled cups while others remain standing. It speaks to sorrow, regret, or disappointment. This card honors your need to mourn, but also gently reminds you that not all is lost and that healing begins by noticing what still remains.'),
('Six of Cups', 'Minor - Cups',
 'Nostalgia, memories, innocence, reconnecting',
 'The Six of Cups returns to sweeter times, childhood memories, or simple joys. It may suggest reconnecting with the past, old friends, or familiar places. This card encourages you to draw comfort and inspiration from innocence without becoming stuck in what used to be.'),
('Seven of Cups', 'Minor - Cups',
 'Choices, illusions, fantasy, wishful thinking',
 'The Seven of Cups offers many tempting visions, not all of them real. You may be overwhelmed by options, desires, or fantasies. This card calls you to ground your dreams in clarity, discern what truly matters, and commit to a realistic path.'),
('Eight of Cups', 'Minor - Cups',
 'Walking away, seeking deeper meaning, departure',
 'The Eight of Cups turns away from what no longer satisfies the heart. You may feel called to leave behind familiar but empty situations. This card invites you to pursue deeper meaning, even if it requires discomfort, distance, or solitary exploration.'),
('Nine of Cups', 'Minor - Cups',
 'Satisfaction, emotional comfort, wish fulfillment',
 'The Nine of Cups is often called the wish card, reflecting contentment and emotional pleasure. You may be enjoying the results of previous efforts or feeling proud of how far you have come. This card encourages gratitude and mindful enjoyment of your blessings.'),
('Ten of Cups', 'Minor - Cups',
 'Harmony, family, emotional fulfillment',
 'The Ten of Cups shows a scene of shared joy, harmony, and long term emotional security. It points to loving relationships, chosen family, or a deep sense of belonging. This card invites you to nurture the connections that bring you genuine peace and happiness.'),
('Page of Cups', 'Minor - Cups',
 'Creativity, curiosity, emotional openness',
 'The Page of Cups approaches life with a tender heart and imaginative spirit. New feelings, messages, or creative ideas may arise in unexpected ways. This card encourages you to stay open, playful, and receptive to emotional and artistic inspiration.'),
('Knight of Cups', 'Minor - Cups',
 'Romantic pursuit, idealism, following the heart',
 'The Knight of Cups follows dreams and emotions with poetic intensity. You may be drawn to romance, beauty, or a heartfelt quest. This card invites you to listen to your heart, while also balancing idealism with grounded awareness.'),
('Queen of Cups', 'Minor - Cups',
 'Compassion, emotion, nurturing intuition',
 'The Queen of Cups is deeply intuitive, empathetic, and emotionally aware. She holds space for feelings without judgment and offers gentle support. This card encourages you to trust your inner sense, practice compassion, and honor the emotional landscape within and around you.'),
('King of Cups', 'Minor - Cups',
 'Emotional balance, wisdom, diplomacy, maturity',
 'The King of Cups sits calmly amid shifting waters. He has learned to feel deeply without being overwhelmed. This card calls you to lead with emotional maturity, respond with empathy, and maintain steady presence in the face of turbulence.');

-- Swords
INSERT INTO tarot_cards (name, arcana, short_meaning, full_summary) VALUES
('Ace of Swords', 'Minor - Swords',
 'Breakthrough, clarity, truth, new ideas',
 'The Ace of Swords cuts through confusion with sharp insight. It signals a mental breakthrough, clear communication, or a new perspective. This card invites you to speak truth, think critically, and use your mind as a tool for clarity rather than conflict.'),
('Two of Swords', 'Minor - Swords',
 'Stalemate, difficult decisions, blocked emotions',
 'The Two of Swords sits at an impasse, blindfolded between choices. You may feel stuck, avoiding a decision, or unsure what to feel. This card encourages you to seek more information, acknowledge your emotions, and bravely move toward resolution.'),
('Three of Swords', 'Minor - Swords',
 'Heartbreak, sorrow, emotional pain',
 'The Three of Swords pierces the heart with pain, grief, or disappointment. Words, thoughts, or events may have caused hurt. This card asks you to allow your feelings, learn from the experience, and trust that healing is possible even when the heart feels broken.'),
('Four of Swords', 'Minor - Swords',
 'Rest, recovery, retreat, quieting the mind',
 'The Four of Swords lies in stillness, seeking rest after struggle. You may need a mental break, solitude, or spiritual retreat. This card invites you to step back, restore your energy, and let your mind settle before taking further action.'),
('Five of Swords', 'Minor - Swords',
 'Conflict, tension, winning at a cost',
 'The Five of Swords shows a hollow victory, where someone wins but harmony is lost. Arguments, ego battles, or unkind tactics may be present. This card suggests reflecting on how you handle conflict and choosing integrity over short term triumph.'),
('Six of Swords', 'Minor - Swords',
 'Transition, moving on, healing journey',
 'The Six of Swords travels across calmer waters after difficulty. You may be leaving behind a painful chapter or shifting your mindset. This card encourages you to accept help if offered and to trust the gradual process of healing and transition.'),
('Seven of Swords', 'Minor - Swords',
 'Deception, strategy, acting alone',
 'The Seven of Swords moves quietly, hinting at secrecy or stealth. This can point to hidden motives, half truths, or the need for careful planning. This card asks you to examine where honesty, strategy, and self reliance are needed, and where deception may be causing harm.'),
('Eight of Swords', 'Minor - Swords',
 'Restriction, fear, mental entrapment',
 'The Eight of Swords stands bound and blindfolded in a prison of thoughts. You may feel trapped by fear, self doubt, or limiting beliefs. This card reminds you that many of these barriers are mental, and that small shifts in perspective can open paths to freedom.'),
('Nine of Swords', 'Minor - Swords',
 'Anxiety, worry, sleepless thoughts',
 'The Nine of Swords sits awake in the night, distressed by worries and imagined scenarios. Anxiety or guilt may weigh heavily on your mind. This card encourages you to seek support, challenge unhelpful thoughts, and remember that your fears are not the full truth.'),
('Ten of Swords', 'Minor - Swords',
 'Endings, collapse, hitting rock bottom',
 'The Ten of Swords depicts a painful ending, a sense that something has definitively fallen apart. Though harsh, it signals that the worst of a situation has already happened. This card invites you to let go, accept reality, and look for the first signs of a new dawn.'),
('Page of Swords', 'Minor - Swords',
 'Curiosity, vigilance, new ideas',
 'The Page of Swords is alert, inquisitive, and eager to learn. You may be gathering information, exploring new concepts, or testing your voice. This card encourages honest questions, clear communication, and mindful observation of how your words affect others.'),
('Knight of Swords', 'Minor - Swords',
 'Fast action, assertiveness, ambition',
 'The Knight of Swords charges ahead with sharp focus and urgency. You may feel driven to act quickly, argue a point, or pursue a goal with intensity. This card advises using your intellect with care, balancing speed with thoughtfulness and respect.'),
('Queen of Swords', 'Minor - Swords',
 'Honesty, clarity, independence, intellect',
 'The Queen of Swords values truth, logic, and direct communication. She can see through confusion and cut away what is unnecessary. This card invites you to speak clearly, set firm boundaries, and use both heart and mind when making judgments.'),
('King of Swords', 'Minor - Swords',
 'Authority, truth, clear thinking, logic',
 'The King of Swords represents disciplined intellect and fair analysis. He makes decisions based on reason, ethics, and a broad perspective. This card calls you to lead with mental clarity, honest words, and a commitment to justice.');

-- Pentacles
INSERT INTO tarot_cards (name, arcana, short_meaning, full_summary) VALUES
('Ace of Pentacles', 'Minor - Pentacles',
 'New financial or material opportunity, prosperity',
 'The Ace of Pentacles plants a seed in the material world. It can signal new work, income, health routines, or practical opportunities. This card invites you to nurture this potential with consistent effort and grounded planning.'),
('Two of Pentacles', 'Minor - Pentacles',
 'Balance, multitasking, adapting',
 'The Two of Pentacles juggles tasks and priorities in constant motion. You may be managing many responsibilities or navigating change. This card encourages flexibility, time management, and a playful attitude as you seek balance in daily life.'),
('Three of Pentacles', 'Minor - Pentacles',
 'Teamwork, skill building, collaboration',
 'The Three of Pentacles shows people working together on a shared project. It highlights cooperation, craft, and recognition of individual talents. This card suggests that your skills grow stronger when you collaborate and welcome constructive feedback.'),
('Four of Pentacles', 'Minor - Pentacles',
 'Control, security, holding tightly, conservatism',
 'The Four of Pentacles grips resources tightly, seeking safety and control. You may be holding on to money, possessions, or habits out of fear. This card asks you to consider where caution is wise and where generosity or openness could create more flow.'),
('Five of Pentacles', 'Minor - Pentacles',
 'Hardship, financial struggle, feeling left out',
 'The Five of Pentacles walks through a cold landscape of scarcity or exclusion. You may be facing financial strain, health concerns, or emotional isolation. This card reminds you to look for sources of support and to remember that your current hardship is not your entire story.'),
('Six of Pentacles', 'Minor - Pentacles',
 'Generosity, charity, giving and receiving',
 'The Six of Pentacles shows an exchange of resources and care. It may point to charity, support, or fair distribution of what you have. This card invites you to reflect on your role in the cycle of giving and receiving, and to act with balance and kindness.'),
('Seven of Pentacles', 'Minor - Pentacles',
 'Patience, long-term investment, assessment',
 'The Seven of Pentacles pauses to evaluate progress. You may be waiting for results of your work or questioning where to invest your energy. This card suggests patient persistence, thoughtful review, and possible adjustments to your long term plans.'),
('Eight of Pentacles', 'Minor - Pentacles',
 'Skill mastery, focused work, improvement',
 'The Eight of Pentacles diligently hones a craft through repetition and care. It represents learning, practice, and gradual mastery. This card encourages you to commit to your work, refine your abilities, and take pride in steady improvement.'),
('Nine of Pentacles', 'Minor - Pentacles',
 'Self-sufficiency, luxury, financial independence',
 'The Nine of Pentacles enjoys the results of sustained effort and wise choices. It reflects self reliance, comfort, and an appreciation of beauty. This card invites you to recognize your achievements, cultivate self respect, and allow yourself to enjoy what you have built.'),
('Ten of Pentacles', 'Minor - Pentacles',
 'Legacy, long-term success, family wealth',
 'The Ten of Pentacles speaks to lasting security, heritage, and shared resources. It can point to family support, long term investments, or community stability. This card encourages you to think in terms of legacy and to build structures that endure beyond the present moment.'),
('Page of Pentacles', 'Minor - Pentacles',
 'Manifestation, learning, new opportunities',
 'The Page of Pentacles studies a coin with focused curiosity. It suggests new chances to learn, earn, or build something tangible. This card invites you to approach your goals as a student, open to instruction and committed to practical steps.'),
('Knight of Pentacles', 'Minor - Pentacles',
 'Hard work, responsibility, steady progress',
 'The Knight of Pentacles moves slowly but surely, dedicated to the task at hand. He values reliability, routine, and thorough effort. This card encourages patience, persistence, and attention to detail as you work toward your objectives.'),
('Queen of Pentacles', 'Minor - Pentacles',
 'Practicality, nurturing, financial stability',
 'The Queen of Pentacles blends practicality with warmth and care. She creates a safe, comfortable environment and manages resources wisely. This card invites you to tend to your home, body, and finances with grounded kindness and steady support.'),
('King of Pentacles', 'Minor - Pentacles',
 'Abundance, leadership, security, wealth',
 'The King of Pentacles represents mature stewardship of material resources. He builds stability through patience, discipline, and strategic planning. This card calls you to lead in practical matters, invest wisely, and create a secure foundation for yourself and others.');
